DELIMITER //

DROP TRIGGER AI_LOG_CREATE_PRODUCT//
CREATE TRIGGER AI_LOG_CREATE_PRODUCT AFTER INSERT
  ON PRODUCTS FOR EACH ROW
BEGIN
  INSERT INTO LOGS VALUES (CONCAT(NEW.NAME,' CREATED BY ',NEW.CREATED_BY, 
    ' ON ', NOW()));
END//

CREATE TRIGGER AU_LOG_UPDATE_PRODUCT AFTER UPDATE
  ON PRODUCTS FOR EACH ROW
BEGIN
  INSERT INTO LOGS VALUES (CONCAT(OLD.NAME, ' WAS UPDATED TO ',NEW.NAME,
    ' BY ',NEW.CREATED_BY,' ON ', NOW()));
END//

CREATE TRIGGER AD_LOG_DELETE_PRODUCT AFTER DELETE
  ON PRODUCTS FOR EACH ROW
BEGIN
  INSERT INTO LOGS VALUES (CONCAT(OLD.NAME, ' WAS DELETED ON ', NOW()));
END//


INSERT INTO PRODUCTS VALUES ('PRODUCT C','JUAN DE LA CRUZ'),
  ('PRODUCT B','JUAN DE LA CRUZ'),
  ('PRODUCT D','JUAN DE LA CRUZ');

UPDATE PRODUCTS SET 
    NAME = 'PRODUCT X'
  WHERE NAME = 'PRODUCT A'


CREATE TABLE PRODUCTS (
  NAME VARCHAR(100),
  CREATED_BY VARCHAR(100)
);

CREATE TABLE LOGS (
  LOG TEXT
);


CREATE A LOG THAT SOULD PROVIDE THE ACTIVITIES FOR THE PRODUCTS
  EXAMPLE
    PRODUCT A CREATED BY USER A ON 2025-01-01 
    PRODUCT A WAS UPDATED FROM PRODUCT A PRODUCT A1 BY USER A ON 2025-01-01
    PRODUCT A WAS DELETED FROM PRODUCTS TABLE BY USER A ON 2025-01-01